#!/bin/sh

./readme_generate
./readme_md2rst

git add --all .
git commit
git push

python3 setup.py sdist upload --sign --identity fabian@portantier.com

python3 setup.py sdist
rm -Rf deb_dist
python setup.py --command-packages=stdeb.command bdist_deb

