#!/bin/sh

./readme_generate

git add --all .
git commit
git push

python3 setup.py sdist upload --sign --identity fabian@portantier.com

# Fix the readme problem - Step 1
#mv README.rst _README.rst
#sed -i s/README.rst/README.txt/g setup.py

# Main work
python3 setup.py sdist
rm -Rf deb_dist
python3 setup.py --command-packages=stdeb.command bdist_deb

# Fix the readme problem - Step 2
#mv _README.rst README.rst
#sed -i s/README.txt/README.rst/g setup.py

